apiVersion: v1
kind: Service
metadata:
  name: k8s-observability-prometheus-grafana
spec:
  type: NodePort
  selector:
    app: k8s-observability-prometheus-grafana
  ports:
    - port: 80
      targetPort: 9696
      protocol: TCP